export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO_COMPLETED = 'UPDATE_TODO_COMPLETED';
export const UPDATE_TODO_TEXT = 'UPDATE_TODO_TEXT';
export const DELETE_TODO = 'DELETE_TODO';
export const APPEND_TO_TODO_LIST = 'APPEND_TO_TODO_LIST';
